### ISSUE TITLE
Better coding

### ISSUE THREAD

**Issue by Sepehrworklife** [shantia-2007/shantia-k#1]
Hello @shantia-2007,
Hope you are well.
I just wanted to say something so you could write code better,
https://github.com/shantia-2007/shantia-k/blob/62068f4d679333dc65a1b57ae26669c87dbbd970/number%20game.py#L2-L6
It is better to first declare `min` and `max` variables so for the range thing you can use something like:
```
min=0
max=100
range(min,max)
```

Bests wishes to you.

**Comment by shantia-2007** [comment]
Thanks
